[package]
name = "tokio-process"
version = "0.1.3"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/tokio-process"
homepage = "https://github.com/alexcrichton/tokio-process"
documentation = "https://docs.rs/tokio-process"
description = """
An implementation of an asynchronous process management backed futures.
"""
categories = ["asynchronous"]

[badges]
travis-ci = { repository = "alexcrichton/tokio-process" }
appveyor = { repository = "alexcrichton/tokio-process" }

[dependencies]
futures = "0.1.11"
mio = "0.6.5"
tokio-core = "0.1.6"
tokio-io = "0.1"

[dev-dependencies]
env_logger = { version = "0.3", default-features = false }
log = "0.3"

byteorder = "*"
bytes = "*"
tokio-proto = "*"
tokio-service = "*"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
mio-named-pipes = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
tokio-signal = "0.1"
