(function() {var implementors = {};
implementors["tokio_process"] = [{text:"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tokio_process/struct.Child.html\" title=\"struct tokio_process::Child\">Child</a>",synthetic:true,types:["tokio_process::Child"]},{text:"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tokio_process/struct.WaitWithOutput.html\" title=\"struct tokio_process::WaitWithOutput\">WaitWithOutput</a>",synthetic:true,types:["tokio_process::WaitWithOutput"]},{text:"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tokio_process/struct.StatusAsync.html\" title=\"struct tokio_process::StatusAsync\">StatusAsync</a>",synthetic:true,types:["tokio_process::StatusAsync"]},{text:"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tokio_process/struct.OutputAsync.html\" title=\"struct tokio_process::OutputAsync\">OutputAsync</a>",synthetic:true,types:["tokio_process::OutputAsync"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tokio_process/struct.ChildStdin.html\" title=\"struct tokio_process::ChildStdin\">ChildStdin</a>",synthetic:true,types:["tokio_process::ChildStdin"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tokio_process/struct.ChildStdout.html\" title=\"struct tokio_process::ChildStdout\">ChildStdout</a>",synthetic:true,types:["tokio_process::ChildStdout"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tokio_process/struct.ChildStderr.html\" title=\"struct tokio_process::ChildStderr\">ChildStderr</a>",synthetic:true,types:["tokio_process::ChildStderr"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
